apiVersion: vpc.tencentcloud.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: tencent-cloud-default-vpc
spec:
  forProvider:
    cidrBlock: "10.0.0.0/16"
    name: "default-vpc"
  providerConfigRef:
    name: tencent-cloud-default-provider-config
